# Generated by Django 5.2.6 on 2025-10-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
